language: minimal

services:
    docker

before_install:
  pip install pycodestyle --user

jobs:
    include:
      - stage: backend-lint
        script: pycodestyle --max-line-length=200 --exclude=python3.8 .
      - stage: ui-lint
        script: make ui.lint
      - stage: backend-proxy-lint
        script: make backend-proxy.lint
      - stage: backend-test
        script: make backend.test
        after_Script: make clean.all
